[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev -- --port 3000"
  targetPort = 3000
  port = 8888
  functions = "netlify/functions"
  
[[scheduled.functions]]
  name = "push-reminders"
  schedule = "*/1 * * * *"
